/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as WorkspacesWorkspaceIdRouteImport } from './routes/workspaces.$workspaceId'
import { Route as WorkspacesWorkspaceIdIndexRouteImport } from './routes/workspaces.$workspaceId.index'
import { Route as WorkspacesWorkspaceIdLiveRouteImport } from './routes/workspaces.$workspaceId.live'
import { Route as WorkspacesWorkspaceIdRecordingsRouteImport } from './routes/workspaces.$workspaceId.recordings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesWorkspaceIdRoute = WorkspacesWorkspaceIdRouteImport.update({
  id: '/workspaces/$workspaceId',
  path: '/workspaces/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesWorkspaceIdIndexRoute =
  WorkspacesWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspacesWorkspaceIdRoute,
  } as any)
const WorkspacesWorkspaceIdLiveRoute =
  WorkspacesWorkspaceIdLiveRouteImport.update({
    id: '/live',
    path: '/live',
    getParentRoute: () => WorkspacesWorkspaceIdRoute,
  } as any)
const WorkspacesWorkspaceIdRecordingsRoute =
  WorkspacesWorkspaceIdRecordingsRouteImport.update({
    id: '/recordings',
    path: '/recordings',
    getParentRoute: () => WorkspacesWorkspaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRouteWithChildren
  '/workspaces/$workspaceId/live': typeof WorkspacesWorkspaceIdLiveRoute
  '/workspaces/$workspaceId/recordings': typeof WorkspacesWorkspaceIdRecordingsRoute
  '/workspaces/$workspaceId/': typeof WorkspacesWorkspaceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/workspaces/$workspaceId/live': typeof WorkspacesWorkspaceIdLiveRoute
  '/workspaces/$workspaceId/recordings': typeof WorkspacesWorkspaceIdRecordingsRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRouteWithChildren
  '/workspaces/$workspaceId/live': typeof WorkspacesWorkspaceIdLiveRoute
  '/workspaces/$workspaceId/recordings': typeof WorkspacesWorkspaceIdRecordingsRoute
  '/workspaces/$workspaceId/': typeof WorkspacesWorkspaceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/workspaces/$workspaceId'
    | '/workspaces/$workspaceId/live'
    | '/workspaces/$workspaceId/recordings'
    | '/workspaces/$workspaceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/workspaces/$workspaceId/live'
    | '/workspaces/$workspaceId/recordings'
    | '/workspaces/$workspaceId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/workspaces/$workspaceId'
    | '/workspaces/$workspaceId/live'
    | '/workspaces/$workspaceId/recordings'
    | '/workspaces/$workspaceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  WorkspacesWorkspaceIdRoute: typeof WorkspacesWorkspaceIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$workspaceId': {
      id: '/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof WorkspacesWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$workspaceId/': {
      id: '/workspaces/$workspaceId/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/'
      preLoaderRoute: typeof WorkspacesWorkspaceIdIndexRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdRoute
    }
    '/workspaces/$workspaceId/live': {
      id: '/workspaces/$workspaceId/live'
      path: '/live'
      fullPath: '/workspaces/$workspaceId/live'
      preLoaderRoute: typeof WorkspacesWorkspaceIdLiveRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdRoute
    }
    '/workspaces/$workspaceId/recordings': {
      id: '/workspaces/$workspaceId/recordings'
      path: '/recordings'
      fullPath: '/workspaces/$workspaceId/recordings'
      preLoaderRoute: typeof WorkspacesWorkspaceIdRecordingsRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdRoute
    }
  }
}

interface WorkspacesWorkspaceIdRouteChildren {
  WorkspacesWorkspaceIdLiveRoute: typeof WorkspacesWorkspaceIdLiveRoute
  WorkspacesWorkspaceIdRecordingsRoute: typeof WorkspacesWorkspaceIdRecordingsRoute
  WorkspacesWorkspaceIdIndexRoute: typeof WorkspacesWorkspaceIdIndexRoute
}

const WorkspacesWorkspaceIdRouteChildren: WorkspacesWorkspaceIdRouteChildren = {
  WorkspacesWorkspaceIdLiveRoute: WorkspacesWorkspaceIdLiveRoute,
  WorkspacesWorkspaceIdRecordingsRoute: WorkspacesWorkspaceIdRecordingsRoute,
  WorkspacesWorkspaceIdIndexRoute: WorkspacesWorkspaceIdIndexRoute,
}

const WorkspacesWorkspaceIdRouteWithChildren =
  WorkspacesWorkspaceIdRoute._addFileChildren(
    WorkspacesWorkspaceIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  WorkspacesWorkspaceIdRoute: WorkspacesWorkspaceIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
